#!/usr/bin/env python

# Reducing noise in protein multialignments
# Copyright (C) 2012 Gokcen Eraslan, Basak Eraslan, Javeria Ali
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import sys
import argparse
import os
import importlib
from collections import Counter

# Biopython is used to parse and manipulate fasta formatted MSA files
from Bio import AlignIO, Align, Seq, SeqRecord


# matlab style indexing i.e.: x = 'AGCGAGGC'; index_string(x, [0, 3, 4]-> 'AGA'
index_string = lambda string, i: ''.join([string[x] for x in i])


def is_noisy(column):
    """Determines whether given column is noisy or not"""

    # Counter is a neat class to convert a sequence into a dictionary holding
    # the count of each item. Here is an example Counter of a msa column:
    # Counter({'S': 7, 'K': 3, 'N': 2, 'D': 1, 'Q': 1, 'R': 1, 'T': 1})

    counter = Counter(column)
    col_length = len(column)

    # there are more than 50% indels
    if counter["-"] > col_length / 2:
        return True

    # at least 50% of amino acids are unique
    if len(counter) >= col_length / 2:
        return True

    if "-" in counter:
        counter.pop("-")

    # no amino acid appears more than twice
    if not [v for v in counter.values() if v > 2]:
        return True

    return False


def filter_noise_in_columns(msa, noise_func):
    """Filters out the columns if given callable returns False"""

    num_columns = len(msa[0])
    valid_columns = [col for col in range(num_columns)
                         if not noise_func(msa[:, col])]

    assert valid_columns, "All columns seem noisy, exiting..."

    new_msa = []

    for record in msa:
        new_msa.append(SeqRecord.SeqRecord(
                       Seq.Seq(index_string(record.seq, valid_columns)),
                               record.id, record.name, record.description))

    return Align.MultipleSeqAlignment(new_msa)


def generate_phylo_tree(msa, outfilename, format, image_format, tree_module):
    """Generates phylogenetic tree from given sequence alignment file."""

    # PyCogent is used to generate phylogenetic tree from the fasta files
    import cogent

    # ETE toolkit is used to render newick trees as images
    import ete2

    aln = cogent.LoadSeqs(data=msa,
                          moltype=cogent.PROTEIN,
                          aligned=True,
                          label_to_name=lambda x: x.split()[0])

    assert tree_module in ("fasttree", "clearcut", "clustalw",
                           "muscle", "raxml"), "Given tree generator is " \
                           "not supported."

    tree_generator = importlib.import_module("cogent.app.%s" % tree_module)
    tree = tree_generator.build_tree_from_alignment(aln, cogent.PROTEIN)
    tree.writeToFile(outfilename, format=format)

    ete_tree = ete2.PhyloTree(outfilename, msa)
    tree_filename, ext = os.path.splitext(outfilename)
    tree_filename += ".%s" % image_format

    ts = ete2.TreeStyle()
    ts.show_leaf_name = True
    ts.show_branch_length = True
    ts.show_branch_support = True

    ete_tree.render(tree_filename, w=1200, units="px", tree_style=ts)


def main():
    """Main function of the program. Pretty explanatory, eh."""

    parser = argparse.ArgumentParser(description="Reducing noise in protein "
                                                 "multialignments")

    parser.add_argument("-i", "--input", metavar="INPUT_ALIGNMENT_FILE",
                        help="Input file from which the noise to be "
                        "reduced. By default, stdin is used.")

    parser.add_argument("-o", "--output", metavar="OUTPUT_ALIGNMENT_FILE",
                        help="Name of the output file to be created upon the "
                        "noise reduction process. stdout is used if not "
                        "specified.")

    parser.add_argument("-I", "--input-format", metavar="INPUT_ALIGNMENT_"
                        "FORMAT", help="Input file format, \"fasta\" is the "
                        "default. Available formats: clustal, phylip, "
                        "stockholm, emboss.")

    parser.add_argument("-O", "--output-format", metavar="OUTPUT_ALIGNMENT_"
                        "FORMAT", help="Output file format, \"fasta\" is the "
                        "default. Available formats: clustal, phylip, "
                        "stockholm, emboss.")

    parser.add_argument("-d", "--output-tree-reduced", metavar="REDUCED_"
                        "OUTPUT_TREE_FILE", help="Phylogenetic tree is "
                        "generated from the noise-reduced alignment file.")

    parser.add_argument("-g", "--output-tree-original", metavar="ORIGINAL_"
                        "OUTPUT_TREE_FILE", help="Phylogenetic tree is "
                        "generated from the original alignment file.")

    parser.add_argument("-T", "--tree-format",
                        help="File format of output tree files. Default is "
                        "newick, alternative format is xml.",
                        default="newick")

    parser.add_argument("-R", "--tree-rendering-format",
                        help="Image format to be used in rendering generated "
                        "trees. This option is used with the --output-tree-* "
                        "options. Default value is png. Alternative formats "
                        "are pdf and svg.",
                        default="png")

    parser.add_argument("-b", "--tree-generator",
                        help="Use given program to generate phylogenetic "
                        "trees. Default is fasttree. Alternatives are: "
                        "clearcut, clustalw, muscle and raxml. ",
                        default="fasttree")

    args = parser.parse_args()

    if args.input:
        input_file = open(args.input, "r")
    else:
        input_file = sys.stdin

    if args.output:
        output_file = open(args.output, "w")
    else:
        output_file = sys.stdout

    input_format = "fasta" if not args.input_format else args.input_format
    output_format = "fasta" if not args.output_format else args.output_format

    original_msa = AlignIO.read(input_file, input_format)
    reduced_msa = filter_noise_in_columns(original_msa, is_noisy)

    AlignIO.write(reduced_msa, output_file, output_format)

    if args.output:
        output_file.close()

    tree_format = "newick" if not args.tree_format else args.tree_format
    tree_rendering_format = ("png" if not args.tree_rendering_format
                             else args.tree_rendering_format)

    tree_generator = ("fasttree" if not args.tree_generator else
                     args.tree_generator.lower())

    if args.output_tree_reduced:
        generate_phylo_tree(reduced_msa.format("fasta"),
                            args.output_tree_reduced,
                            tree_format,
                            tree_rendering_format,
                            tree_generator)

    if args.output_tree_original:
        generate_phylo_tree(original_msa.format("fasta"),
                            args.output_tree_original,
                            tree_format,
                            tree_rendering_format,
                            tree_generator)


if __name__ == '__main__':
    main()
